os:
  - Visual Studio 2019

configuration:
  - Debug

platform:
  - Win64

environment:
  MSVC_DEFAULT_OPTIONS: ON
  MYSQL_PWD: "Password12!"

services:
  - mysql

before_build:
  - set PATH="C:\\Program Files\\MySQL\\MySQL Server 5.7\\bin";%PATH%
  - cd c:\projects\sapphire
  - git submodule update --init
  - mkdir build
  - cd build
  - cmake .. -G "Visual Studio 16 2019" -A x64
  - cmake --build . --target ALL_BUILD --config RelWithDebInfo

build_script:
  - cd bin  
  - copy "C:\Program Files\MySQL\MySQL Server 5.7\lib\libmysql.dll" libmysql.dll
  - sh sql_import.sh
