---
language: c++

sudo: enabled

git:
  depth: 5

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - g++-8
      env:
      - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
      - CXX=g++-8

# Setup cache
cache:
  directories:
    - build
    - .mtime_cache

# Setup build matrix and dependencies
before_install:
  - eval "${MATRIX_EVAL}"
  - gem install mtime_cache --no-document
  - sudo apt-get update
  - sudo apt-get install -y libmysqlclient-dev

# Build steps
script:
  - $CXX --version
  - mtime_cache src/**/*.{%{cpp}} -c .mtime_cache/cache.json
  - mkdir -p build
  - cd build
  - cmake .. && make -j 3
  - cd bin
  - bash sql_import.sh
